# @file
# .travis.yml - PKP Plugins Integration

dist: bionic
os: linux
language: php

addons:
  postgresql: "9.5"
  apt:
    update: true

sudo: required

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1.0
env:
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=mysql
  - APPLICATION=ojs BRANCH=stable-3_3_0 TEST=pgsql

install:
  # Prepare OJS environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/themes/immersion
  # Install OJS & prep data environment
  - $(npm bin)/cypress run --spec "cypress/tests/data/*.spec.js,cypress/tests/data/60-content/VkarbasizaedSubmission.spec.js"

script:
  - $(npm bin)/cypress run --config integrationFolder=plugins/themes/immersion/cypress/tests/functional

after_failure:
  - cat error.log
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout
